/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import code.Nodo;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Font;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GestorEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form listas_simples
     */
    
    private Nodo inicio;
    private Nodo pFound;
    private int num;
    
    public GestorEmpleado() {
        initComponents();
        setTitle("Registro de empleados");
        Encabezado();
        Deshabilitar();
        TextAreaDatos.setEditable(false);
        inicio = null;
        num = 0;
        setResizable(false);
    }
    
    void Encabezado(){
        TextAreaDatos.setFont(new Font("monospaced", Font.PLAIN, 18));
        TextAreaDatos.setText("");
        TextAreaDatos.append("");
        TextAreaDatos.append("\tN°\tCodigo\tNombres y Apellidos\tSueldos\n");
        TextAreaDatos.append("\t-----------------------------------------------------------------------------------------\n");
    }
    
    void Habilitar(){
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(false);
    }
    
    void Deshabilitar(){
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
    }
    
    void LimpiarEntradas(){
        TextFieldCodigo.setText("");
        TextFieldNombre.setText("");
        TextFieldSueldo.setText("");
        TextFieldCodigo.requestFocus();
    }
    
    public void verDatos(){
        DecimalFormat df = new DecimalFormat("####.00");
        String cod, nom, sue;
        Nodo aux = inicio;
        num = 0;
        TextAreaDatos.setText("");
        Encabezado();
        while(aux != null){
            cod = aux.codigo;
            nom = aux.nombre;
            sue = aux.sueldo;
            num++;
            String numero = String.valueOf(num);
            sue = df.format(Double.valueOf(sue));
            System.out.println("\t"+numero+"\t"+cod+"\t"+nom+"\t"+sue);
            TextAreaDatos.append("\t"+numero+"\t"+cod+"\t"+nom+"\t"+sue+"\n");
            aux = aux.sig;
        }
    }
    
    public Nodo buscar(String cod){
        Nodo pos = inicio;
        while(pos != null  && !cod.equalsIgnoreCase(pos.codigo)){
            pos = pos.sig;
        }
        return pos;
    }
    
    Nodo Buscar(Nodo inicio, String cod){
        Nodo pos = inicio;
        while(pos!=null && !cod.equalsIgnoreCase(pos.codigo)){
            pos=pos.sig;
        }
        return pos;
    }
    
    void eliminar(Nodo actual){
       Nodo anterior = inicio;
       while(anterior.sig != actual && anterior.sig != null){
           anterior = anterior.sig;
       }
       if(actual != null){
           if(anterior == actual){
               inicio = actual.sig;
           }else{
               anterior.sig = actual.sig;
           }
       }
    }
    
    Nodo InsertaInicio(Nodo inicio ,String cod, String nom,String suel){
        Nodo nuevo = new Nodo(cod, nom, suel);
        nuevo.sig=inicio;
        inicio=nuevo;
        return inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextFieldSueldo = new javax.swing.JTextField();
        TextFieldCodigo = new javax.swing.JTextField();
        TextFieldNombre = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDatos = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("Gestor de empleados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setText("Sueldo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel3.setText("Codigo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        TextFieldSueldo.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jPanel1.add(TextFieldSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 350, 30));

        TextFieldCodigo.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jPanel1.add(TextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 350, 30));

        TextFieldNombre.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jPanel1.add(TextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 350, 30));

        btnSalir.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 120, 30));

        btnActualizar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(52, 152, 219));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 120, 30));

        btnEliminar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 87, 51));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 120, 30));

        btnRestaurar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnRestaurar.setForeground(new java.awt.Color(144, 148, 151));
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 120, 30));

        btnConsultar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 195, 0));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 120, 30));

        btnGuardar.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(46, 204, 113));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 120, 30));

        TextAreaDatos.setEditable(false);
        TextAreaDatos.setBackground(new java.awt.Color(255, 255, 255));
        TextAreaDatos.setColumns(20);
        TextAreaDatos.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        TextAreaDatos.setRows(5);
        TextAreaDatos.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(TextAreaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 790, 150));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel5.setText("Tipo de contrato: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 210, 30));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel6.setText("Monto asignado por movilidad: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jTextField1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 220, 30));

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel7.setText("Minutos de tardanza: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jTextField2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String cod=TextFieldCodigo.getText();
        String nom=TextFieldNombre.getText().toUpperCase();
        String suel=TextFieldSueldo.getText();
        
        inicio=InsertaInicio(inicio, cod, nom, suel);
        LimpiarEntradas();
        verDatos();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        pFound.codigo = TextFieldCodigo.getText();
        pFound.nombre = TextFieldNombre.getText().toUpperCase();
        pFound.sueldo = TextFieldSueldo.getText();
        LimpiarEntradas();
        Deshabilitar();
        verDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        String cod=TextFieldCodigo.getText();
        if(cod.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Ingrese un codigo por favor");
        }else{
            pFound = Buscar(inicio,cod);
            if(pFound!=null){
                TextFieldNombre.setText(pFound.nombre);
                TextFieldSueldo.setText(pFound.sueldo);
                Habilitar();
            }else{
                JOptionPane.showMessageDialog(this, "El codigo: "+cod+", no esta en la lista..");
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminar(pFound);
        TextFieldCodigo.setText("");
        TextFieldNombre.setText("");
        TextFieldSueldo.setText("");
        verDatos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        // TODO add your handling code here:
        LimpiarEntradas();
        Deshabilitar();
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea TextAreaDatos;
    public javax.swing.JTextField TextFieldCodigo;
    public javax.swing.JTextField TextFieldNombre;
    public javax.swing.JTextField TextFieldSueldo;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnRestaurar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
